version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "8080:8080"
    volumes:
      - .:/go/src/app


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"